-- Fix province: converte nomi estesi e nomi città → sigla 2 lettere maiuscole
-- Copre: nomi province, capoluoghi, comuni frequenti, sigle minuscole/miste

UPDATE clienti
SET provincia = prov.sigla
FROM (
  VALUES
  -- ── Già sigle (minuscole o miste → uppercase) gestite sotto con CASE separato ──
  -- ── Nomi province estesi ──
  ('agrigento','AG'),('alessandria','AL'),('ancona','AN'),('aosta','AO'),
  ('valle d''aosta','AO'),('valle daosta','AO'),
  ('ascoli piceno','AP'),('l''aquila','AQ'),('aquila','AQ'),('arezzo','AR'),
  ('asti','AT'),('avellino','AV'),('bari','BA'),
  ('barletta-andria-trani','BT'),('barletta andria trani','BT'),
  ('belluno','BL'),('benevento','BN'),('bergamo','BG'),('biella','BI'),
  ('bologna','BO'),('bolzano','BZ'),('bozen','BZ'),('brescia','BS'),
  ('brindisi','BR'),('cagliari','CA'),('caltanissetta','CL'),
  ('campobasso','CB'),('caserta','CE'),('catania','CT'),('catanzaro','CZ'),
  ('chieti','CH'),('como','CO'),('cosenza','CS'),('cremona','CR'),
  ('crotone','KR'),('cuneo','CN'),('enna','EN'),('fermo','FM'),
  ('ferrara','FE'),('firenze','FI'),('florence','FI'),
  ('foggia','FG'),('forli-cesena','FC'),('forlì-cesena','FC'),
  ('forli cesena','FC'),('forlì cesena','FC'),
  ('frosinone','FR'),('genova','GE'),('gorizia','GO'),('grosseto','GR'),
  ('imperia','IM'),('isernia','IS'),('la spezia','SP'),('spezia','SP'),
  ('latina','LT'),('lecce','LE'),('lecco','LC'),('livorno','LI'),
  ('lodi','LO'),('lucca','LU'),('macerata','MC'),('mantova','MN'),
  ('massa','MS'),('massa-carrara','MS'),('massa carrara','MS'),
  ('matera','MT'),('messina','ME'),('milano','MI'),('milan','MI'),
  ('modena','MO'),('monza','MB'),('monza e brianza','MB'),
  ('monza brianza','MB'),('napoli','NA'),('novara','NO'),('nuoro','NU'),
  ('oristano','OR'),('padova','PD'),('palermo','PA'),('parma','PR'),
  ('pavia','PV'),('perugia','PG'),('pesaro','PU'),
  ('pesaro e urbino','PU'),('pesaro urbino','PU'),('urbino','PU'),
  ('pescara','PE'),('piacenza','PC'),('pisa','PI'),('pistoia','PT'),
  ('pordenone','PN'),('potenza','PZ'),('prato','PO'),('ragusa','RG'),
  ('ravenna','RA'),('reggio calabria','RC'),('reggio di calabria','RC'),
  ('reggio emilia','RE'),('reggio nell''emilia','RE'),
  ('rieti','RI'),('rimini','RN'),('roma','RM'),('rome','RM'),
  ('rovigo','RO'),('salerno','SA'),('sassari','SS'),('savona','SV'),
  ('siena','SI'),('siracusa','SR'),('sondrio','SO'),('sud sardegna','SU'),
  ('taranto','TA'),('teramo','TE'),('terni','TR'),('torino','TO'),
  ('trapani','TP'),('trento','TN'),('treviso','TV'),('trieste','TS'),
  ('udine','UD'),('varese','VA'),('venezia','VE'),('venice','VE'),
  ('verbano-cusio-ossola','VB'),('verbano cusio ossola','VB'),
  ('verbania','VB'),('vercelli','VC'),('verona','VR'),('vicenza','VI'),
  ('viterbo','VT'),('vibo valentia','VV'),
  -- ── Capoluoghi non-province (città → sigla della propria provincia) ──
  -- Lombardi
  ('abbiategrasso','MI'),('busto arsizio','VA'),('gallarate','VA'),
  ('saronno','VA'),('sesto san giovanni','MI'),('cinisello balsamo','MI'),
  ('monza','MB'),('desio','MB'),('seregno','MB'),('vimercate','MB'),
  ('lissone','MB'),('carate brianza','MB'),
  ('bergamo alta','BG'),('treviglio','BG'),('seriate','BG'),('dalmine','BG'),
  ('brescia','BS'),('chiari','BS'),('darfo boario terme','BS'),('lumezzane','BS'),
  ('garda','BS'),('salo','BS'),('salò','BS'),
  ('lecco','LC'),('merate','LC'),('mandello del lario','LC'),
  ('como','CO'),('cantù','CO'),('mariano comense','CO'),
  ('lodi','LO'),('codogno','LO'),('casalpusterlengo','LO'),
  ('pavia','PV'),('vigevano','PV'),('voghera','PV'),('mortara','PV'),
  ('cremona','CR'),('crema','CR'),('casalmaggiore','CR'),('soresina','CR'),
  ('pandino','CR'),('romanengo','CR'),('rivolta d''adda','CR'),
  ('mantova','MN'),('viadana','MN'),('suzzara','MN'),('guidizzolo','MN'),
  ('sabbioneta','MN'),('castel goffredo','MN'),('ostiglia','MN'),
  ('volta mantovana','MN'),('castiglione delle stiviere','MN'),
  ('porto mantovano','MN'),('curtatone','MN'),('marmirolo','MN'),
  ('gonzaga','MN'),('pegognaga','MN'),('moglia','MN'),
  ('sondrio','SO'),('tirano','SO'),('livigno','SO'),
  ('lecco','LC'),
  -- Piemonte
  ('torino','TO'),('moncalieri','TO'),('collegno','TO'),('rivoli','TO'),
  ('nichelino','TO'),('settimo torinese','TO'),('chieri','TO'),
  ('pinerolo','TO'),('chivasso','TO'),
  ('cuneo','CN'),('alba','CN'),('bra','CN'),('fossano','CN'),('saluzzo','CN'),
  ('mondovi','CN'),('mondovì','CN'),
  ('alessandria','AL'),('novi ligure','AL'),('tortona','AL'),('casale monferrato','AL'),
  ('asti','AT'),('canelli','AT'),
  ('novara','NO'),('borgomanero','NO'),('arona','NO'),
  ('vercelli','VC'),('borgosesia','VC'),
  ('biella','BI'),('cossato','BI'),
  -- Emilia-Romagna
  ('bologna','BO'),('imola','BO'),('casalecchio di reno','BO'),
  ('modena','MO'),('carpi','MO'),('sassuolo','MO'),('formigine','MO'),
  ('mirandola','MO'),('vignola','MO'),
  ('parma','PR'),('fidenza','PR'),('salsomaggiore terme','PR'),
  ('piacenza','PC'),('fiorenzuola d''arda','PC'),('castel san giovanni','PC'),
  ('reggio emilia','RE'),('scandiano','RE'),('guastalla','RE'),('correggio','RE'),
  ('rubiera','RE'),('castellarano','RE'),
  ('ferrara','FE'),('cento','FE'),('comacchio','FE'),
  ('ravenna','RA'),('faenza','RA'),('lugo','RA'),('cervia','RA'),
  ('forli','FC'),('forlì','FC'),('cesena','FC'),('cesenatico','FC'),
  ('rimini','RN'),('riccione','RN'),('cattolica','RN'),
  -- Veneto
  ('verona','VR'),('legnago','VR'),('san bonifacio','VR'),('bussolengo','VR'),
  ('vicenza','VI'),('bassano del grappa','VI'),('schio','VI'),('thiene','VI'),
  ('padova','PD'),('abano terme','PD'),('cittadella','PD'),('este','PD'),
  ('venezia','VE'),('mestre','VE'),('chioggia','VE'),('dolo','VE'),
  ('treviso','TV'),('conegliano','TV'),('castelfranco veneto','TV'),
  ('belluno','BL'),('feltre','BL'),
  ('rovigo','RO'),('adria','RO'),
  -- Toscana
  ('firenze','FI'),('empoli','FI'),('scandicci','FI'),('sesto fiorentino','FI'),
  ('siena','SI'),('poggibonsi','SI'),('montepulciano','SI'),
  ('arezzo','AR'),('sansepolcro','AR'),('cortona','AR'),
  ('pistoia','PT'),('monsummano terme','PT'),
  ('prato','PO'),
  ('lucca','LU'),('viareggio','LU'),('capannori','LU'),
  ('pisa','PI'),('cascina','PI'),('pontedera','PI'),
  ('livorno','LI'),('cecina','LI'),('piombino','LI'),
  ('grosseto','GR'),('orbetello','GR'),
  ('massa','MS'),('carrara','MS'),
  -- Lazio
  ('roma','RM'),('fiumicino','RM'),('guidonia montecelio','RM'),('tivoli','RM'),
  ('velletri','RM'),('pomezia','RM'),('anzio','RM'),
  ('latina','LT'),('terracina','LT'),('aprilia','LT'),('formia','LT'),
  ('frosinone','FR'),('cassino','FR'),('anagni','FR'),
  ('viterbo','VT'),('civitavecchia','RM'),
  ('rieti','RI'),
  -- Campania
  ('napoli','NA'),('giugliano in campania','NA'),('torre del greco','NA'),
  ('salerno','SA'),('nocera inferiore','SA'),('cava de'' tirreni','SA'),
  ('caserta','CE'),('aversa','CE'),('marcianise','CE'),
  ('avellino','AV'),('ariano irpino','AV'),
  ('benevento','BN'),('montesarchio','BN'),
  -- Puglia
  ('bari','BA'),('altamura','BA'),('molfetta','BA'),('bitonto','BA'),
  ('taranto','TA'),('grottaglie','TA'),('martina franca','TA'),
  ('lecce','LE'),('nardò','LE'),('galatina','LE'),
  ('brindisi','BR'),('fasano','BR'),('ostuni','BR'),('francavilla fontana','BR'),
  ('foggia','FG'),('cerignola','FG'),('manfredonia','FG'),
  ('barletta','BT'),('andria','BT'),('trani','BT'),
  -- Sicilia
  ('palermo','PA'),('bagheria','PA'),('monreale','PA'),
  ('catania','CT'),('acireale','CT'),('misterbianco','CT'),
  ('messina','ME'),('barcellona pozzo di gotto','ME'),
  ('siracusa','SR'),('augusto','SR'),('noto','SR'),
  ('ragusa','RG'),('vittoria','RG'),('modica','RG'),
  ('trapani','TP'),('marsala','TP'),('mazara del vallo','TP'),
  ('agrigento','AG'),('porto empedocle','AG'),
  ('caltanissetta','CL'),('gela','CL'),
  ('enna','EN'),('piazza armerina','EN'),
  -- Sardegna
  ('cagliari','CA'),('quartu sant''elena','CA'),('selargius','CA'),
  ('sassari','SS'),('alghero','SS'),('porto torres','SS'),
  ('nuoro','NU'),('dorgali','NU'),
  ('oristano','OR'),
  -- Altre regioni
  ('trento','TN'),('rovereto','TN'),('riva del garda','TN'),
  ('bolzano','BZ'),('merano','BZ'),('bressanone','BZ'),
  ('trieste','TS'),('udine','UD'),('pordenone','PN'),('gorizia','GO'),
  ('genova','GE'),('sanremo','IM'),('savona','SV'),('la spezia','SP'),
  ('perugia','PG'),('foligno','PG'),('spoleto','PG'),('assisi','PG'),
  ('terni','TR'),('orvieto','TR'),
  ('ancona','AN'),('senigallia','AN'),('jesi','AN'),('fabriano','AN'),
  ('pesaro','PU'),('fano','PU'),('urbino','PU'),
  ('macerata','MC'),('civitanova marche','MC'),('recanati','MC'),
  ('ascoli piceno','AP'),('san benedetto del tronto','AP'),
  ('fermo','FM'),('porto san giorgio','FM'),
  ('l''aquila','AQ'),('avezzano','AQ'),('sulmona','AQ'),
  ('chieti','CH'),('lanciano','CH'),('vasto','CH'),
  ('pescara','PE'),('montesilvano','PE'),
  ('teramo','TE'),('giulianova','TE'),
  ('campobasso','CB'),('termoli','CB'),
  ('isernia','IS'),
  ('potenza','PZ'),('melfi','PZ'),
  ('matera','MT'),
  ('cosenza','CS'),('rende','CS'),('corigliano-rossano','CS'),
  ('catanzaro','CZ'),('lamezia terme','CZ'),
  ('reggio calabria','RC'),
  ('crotone','KR'),
  ('vibo valentia','VV'),
  ('carrara','MS')
) AS prov(raw, sigla)
WHERE LOWER(TRIM(clienti.provincia)) = prov.raw
  AND (
    LENGTH(TRIM(clienti.provincia)) > 2
    OR clienti.provincia != UPPER(clienti.provincia)
  );

-- Gestisci sigle già corrette ma minuscole/miste (es. "cr" → "CR", "Mi" → "MI")
UPDATE clienti
SET provincia = UPPER(TRIM(provincia))
WHERE LENGTH(TRIM(provincia)) = 2
  AND provincia ~ '^[A-Za-z]{2}$'
  AND provincia != UPPER(TRIM(provincia));
