-- ═══════════════════════════════════════════════════════════════
-- RIFORNIMENTO — catalogo cosmesi Natyr (104 prodotti)
-- ═══════════════════════════════════════════════════════════════
INSERT INTO rifornimento_catalogo
  (source_sheet, category, product_code, description, pvp, pack_size,
   assortment_cremona, assortment_casalmaggiore, assortment_viadana, sort_order, active, fornitore)
VALUES
  ('Natyr','LINEA ALOE VERA','6243','ACIDO IALURONICO SIERO ALOE',10.0,9,true,true,true,1,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','6709','BAGNO DOCCIA ULTRA SENS. CON PREB.',7.0,1,true,true,true,2,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','7133','FACE MIST SPRAY ALOE',10.0,1,true,true,true,3,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','7929','PROTECTIVE KIT BALS. LABBRA + MANI',10.0,1,true,true,true,4,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','30239','CREMA VISO ALOE',20.0,1,true,true,true,5,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','30240','LATTE DETERGENTE ALOE',10.0,1,true,true,true,6,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','30249','CREMA CORPO ALOE',15.0,1,true,true,true,7,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','30290','CREMA MANI ALOE',7.0,1,true,true,true,8,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','36266','BALSAMO LABBRA ALOE',5.0,6,true,true,true,9,true,'Natyr'),
  ('Natyr','LINEA ALOE VERA','49509','DEODORANTE ALOE',8.0,1,true,true,true,10,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','96','BAGNODOCCIA TÈ VERDE',7.0,1,true,true,true,11,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','113','MASCHERA VISO TÈ VERDE',3.0,20,true,true,true,12,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','7466','SIERO VISO ANTI IMPERFEZIONI',10.0,9,true,true,true,13,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','7467','LOZIONE VISO',10.0,1,true,true,true,14,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','30245','CREMA GEL VISO TÈ VERDE',20.0,1,true,true,true,15,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','30254','CREMA GEL CORPO TÈ VERDE',15.0,1,true,true,true,16,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','30287','DENTIFRICIO GEL TÈ VERDE',5.0,1,true,true,true,17,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','33753','MOUSSE VISO TÈ VERDE',7.0,1,true,true,true,18,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','35016','ACQUA TONICO TÈ VERDE',9.0,1,true,true,true,19,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','41972','CREMA GEL GAMBE PIEDI',10.0,1,true,true,true,20,true,'Natyr'),
  ('Natyr','LINEA AL TÈ VERDE','41973','SALI PEDILUVIO',7.0,1,true,true,true,21,true,'Natyr'),
  ('Natyr','LINEA IBISCO','73','DEOLATTE IBISCO',7.0,1,true,true,true,22,true,'Natyr'),
  ('Natyr','LINEA IBISCO','74','FLUIDA CORPO IBISCO',11.0,1,true,true,true,23,true,'Natyr'),
  ('Natyr','LINEA IBISCO','75','BAGNO DOCCIA IBSICO',7.0,1,true,true,true,24,true,'Natyr'),
  ('Natyr','LINEA IBISCO','107','CREMA MANI IBISCO MINI',5.0,1,true,true,true,25,true,'Natyr'),
  ('Natyr','LINEA IBISCO','110','DETERGENTE INTIMO IBISCO',8.0,1,true,true,true,26,true,'Natyr'),
  ('Natyr','LINEA IBISCO','3928','DETERGENTE VISO SOLIDO',8.0,1,true,true,true,27,true,'Natyr'),
  ('Natyr','LINEA IBISCO','6659','CREMA VISO IDRATANTE E ILLUMINANTE',20.0,1,true,true,true,28,true,'Natyr'),
  ('Natyr','LINEA IBISCO','6660','MOUSSE DETERGENTE',8.0,1,true,true,true,29,true,'Natyr'),
  ('Natyr','LINEA IBISCO','6661','MASCHERA VISO IDRATANTE GLOW',3.0,1,true,true,true,30,true,'Natyr'),
  ('Natyr','LINEA IBISCO','6662','BURRO STRUCCANTE',11.0,1,true,true,true,31,true,'Natyr'),
  ('Natyr','LINEA IBISCO','6707','SIERO VISO ILLUMINANTE',10.0,9,true,true,true,32,true,'Natyr'),
  ('Natyr','LINEA IBISCO','6710','GEL DETERGENTE VISO',9.0,1,true,true,true,33,true,'Natyr'),
  ('Natyr','LINEA IBISCO','8267','FLUIDO VISO SPF CHIARA',15.0,1,true,true,true,34,true,'Natyr'),
  ('Natyr','LINEA IBISCO','8268','FLUIDO VISO SPF SCURA',15.0,1,true,true,true,35,true,'Natyr'),
  ('Natyr','LINEA IBISCO','42104','LATTE TONICO IBISCO',10.0,1,true,true,true,36,true,'Natyr'),
  ('Natyr','LINEA ARGAN','1','SIERO VISO ARGAN',16.0,1,true,true,true,37,true,'Natyr'),
  ('Natyr','LINEA ARGAN','2','CREMA VISO ARGAN',20.0,1,true,true,true,38,true,'Natyr'),
  ('Natyr','LINEA ARGAN','55','OLIO DOCCIA ARGAN',7.0,1,true,true,true,39,true,'Natyr'),
  ('Natyr','LINEA ARGAN','93','STRUCCANTE BIFASICO',10.0,1,true,true,true,40,true,'Natyr'),
  ('Natyr','LINEA ARGAN','109','CREMA MANI ARGAN MINI',5.0,1,true,true,true,41,true,'Natyr'),
  ('Natyr','LINEA ARGAN','3758','BURRO LABBRA ARGAN MELOGRANO',7.0,6,true,true,true,42,true,'Natyr'),
  ('Natyr','LINEA ARGAN','4279','BURRO CREMA CORPO ARGAN',16.0,1,true,true,true,43,true,'Natyr'),
  ('Natyr','LINEA ARGAN','7240','SIERO VISO ARGAN E COLLAGENE VEG.',10.0,9,true,true,true,44,true,'Natyr'),
  ('Natyr','LINEA ARGAN','8062','BALSAMO LABBRA ARGAN',5.0,6,true,true,true,45,true,'Natyr'),
  ('Natyr','LINEA ARGAN','50990','OLIO PURO ARGAN',18.0,1,true,true,true,46,true,'Natyr'),
  ('Natyr','LINEA MANGO PAPAYA','98','SIERO LIFTING MANGO PAPAYA',16.0,1,true,true,true,47,true,'Natyr'),
  ('Natyr','LINEA MANGO PAPAYA','5936','CREMA VISO MANGO E PAPAYA ANTIMACCHIA',20.0,null,null,null,null,48,true,'Natyr'),
  ('Natyr','LINEA MANGO PAPAYA','30284','CREMA VISO MANGO E PAPAYA',20.0,1,true,true,true,49,true,'Natyr'),
  ('Natyr','LINEA MANGO PAPAYA','30285','CONTORNO OCCHI MANGO PAP',11.0,1,true,true,true,50,true,'Natyr'),
  ('Natyr','LINEA KARITÈ','84','CREMA MANI KARITÈ',7.0,1,true,true,true,51,true,'Natyr'),
  ('Natyr','LINEA KARITÈ','45539','CREMA PIEDI KARITÈ',7.0,1,true,true,true,52,true,'Natyr'),
  ('Natyr','LINEA COMMUNITY','50994','DOCCIA SHAMPOO COMMUNITY',12.0,1,true,true,true,53,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3413','SHAMPOO ALOE',10.0,1,true,true,true,54,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3414','SHAMPOO CREMA',10.0,1,true,true,true,55,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3415','SHAMPOO ARGAN',10.0,1,true,true,true,56,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3914','BALSAMO CAPELLI ALOE',10.0,1,true,true,true,57,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3412','SHAMPOO TÈ VERDE',10.0,1,true,true,true,58,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3898','MASCHERA CAPELLI KARITÈ',11.0,1,true,true,true,59,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3899','BALSAMO CAPELLI ARGAN',10.0,1,true,true,true,60,true,'Natyr'),
  ('Natyr','LINEA CAPELLI','3920','BALSAMO CAPELLI TÈ VERDE',10.0,1,true,true,true,61,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','114','MASCHERA VISO ROSA DAM.',3.0,20,true,true,true,62,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','115','SIERO INTENSIVO ROSA DAM',16.0,1,true,true,true,63,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','117','IDROGEL STRUCCANTE ROSA D.',10.0,1,true,true,true,64,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','118','CREMA MULTIF. ROSA DAM.',15.0,1,true,true,true,65,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','3017','CREMA VISO ROSA DAM.',20.0,1,true,true,true,66,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','3018','CONTORNO OCCHI',14.0,1,true,true,true,67,true,'Natyr'),
  ('Natyr','LINEA ROSA DAMASCO','6708','BAGNO DOCCIA SCRUB CON TÈ BIANCO',9.0,1,true,true,true,68,true,'Natyr'),
  ('Natyr','LINEA BLOOMING NIGHT','126','OLIO SIERO VISO NIGHT B.',15.0,1,true,true,true,69,true,'Natyr'),
  ('Natyr','LINEA BLOOMING NIGHT','147','MASCHERA NIGHT B.',3.0,20,true,true,true,70,true,'Natyr'),
  ('Natyr','LINEA BLOOMING NIGHT','6244','CREMA VISO NOTTE',20.0,1,true,true,true,71,true,'Natyr'),
  ('Natyr','LINEA UOMO','102','DOPOBARBA GEL',9.0,1,true,true,true,72,true,'Natyr'),
  ('Natyr','LINEA UOMO','105','BALSAMO MULTIFUNZIONE UOMO',13.0,1,true,true,true,73,true,'Natyr'),
  ('Natyr','LINEA UOMO','129','CREMA UNIVERSALE UOMO',16.0,1,true,true,true,74,true,'Natyr'),
  ('Natyr','LINEA UOMO','4082','CREMA VISO IDRAT. VET./PEPE/GUAR.',18.0,1,true,true,true,75,true,'Natyr'),
  ('Natyr','LINEA UOMO','4084','CREMA DOPOBARBA ULTRA COMFORT',9.0,1,true,true,true,76,true,'Natyr'),
  ('Natyr','LINEA UOMO','4085','SHAMPOO DOCCIA TONIF. VET./PEPE/GU.',7.0,1,true,true,true,77,true,'Natyr'),
  ('Natyr','LINEA UOMO','7930','TRAVELLER - SHAMPOO/CREMA MANI',10.0,1,true,true,true,78,true,'Natyr'),
  ('Natyr','LINEA UOMO','33758','DEODORANTE UOMO',7.0,1,true,true,true,79,true,'Natyr'),
  ('Natyr','LINEA UOMO','33759','DOCCIA SPORT UOMO',7.0,1,true,true,true,80,true,'Natyr'),
  ('Natyr','SAPONI','155','SAPONE PALESTINA ARGILLA ROSSA',7.0,1,true,true,true,81,true,'Natyr'),
  ('Natyr','SAPONI','156','SAPONE PALESTINA ARGILLA VERDE',7.0,1,true,true,true,82,true,'Natyr'),
  ('Natyr','SAPONI','157','SAPONE PALESTINA ARGILLA GIALLA',7.0,1,true,true,true,83,true,'Natyr'),
  ('Natyr','SAPONI','3491','SAPONE RILASSANTE',7.0,1,true,true,true,84,true,'Natyr'),
  ('Natyr','SAPONI','7043','SAPONE THAI SCRUB MELA CANNELLA',6.0,1,true,true,true,85,true,'Natyr'),
  ('Natyr','SAPONI','7044','SAPONE THAI SCRUB RISO ROSSO',6.0,1,true,true,true,86,true,'Natyr'),
  ('Natyr','SAPONI','7045','SAPONE THAI SCRUB YLANG YLANG',6.0,1,true,true,true,87,true,'Natyr'),
  ('Natyr','SAPONI','7046','SAPONE THAI TRIS PROFUMI FRUTTA',7.0,1,true,true,true,88,true,'Natyr'),
  ('Natyr','SAPONI','7047','SAPONE THAI TRIS PROFUMI ERBE',7.0,1,true,true,true,89,true,'Natyr'),
  ('Natyr','SAPONI','7048','SAPONE THAI TRIS PROFUMI FIORI',7.0,1,true,true,true,90,true,'Natyr'),
  ('Natyr','SAPONI','7049','SAPONE THAI SALI HIMALAYA GINEPRO',null,null,null,null,null,91,true,'Natyr'),
  ('Natyr','SAPONI','7051','SAPONE AGRUMI E SPUGNA IN JUTA',7.0,1,true,true,true,92,true,'Natyr'),
  ('Natyr','LINEA SOLIDI PER CAPELLI','3759','SHAMPOO SOL. PURIF. GHASSOUL/TÈ',null,1,true,true,true,93,true,'Natyr'),
  ('Natyr','LINEA SOLIDI PER CAPELLI','3760','BALSAMO SOL. VOLUM. AVOCADO/TÈ',null,1,true,true,true,94,true,'Natyr'),
  ('Natyr','LINEA SOLIDI PER CAPELLI','3761','SHAMPOO SOL. RIEQUIL. ARGAN/JOJOBA',null,1,true,true,true,95,true,'Natyr'),
  ('Natyr','LINEA SOLIDI PER CAPELLI','3762','BALSAMO SOL. NUTRIENTE KARITE/JOJOB.',null,1,true,true,true,96,true,'Natyr'),
  ('Natyr','LINEA SOLIDI PER CAPELLI','5586','SHAMPOO DOCCIA SOL.',null,1,true,true,true,97,true,'Natyr'),
  ('Natyr','LINEA INSTANT IN POLVERE','6245','BAGNODOCCIA MENTA GINEPRO',5.0,1,true,true,true,98,true,'Natyr'),
  ('Natyr','LINEA INSTANT IN POLVERE','6246','BAGNODOCCIA ZENZERO CITRONELLA',5.0,1,true,true,true,99,true,'Natyr'),
  ('Natyr','LINEA INSTANT IN POLVERE','6247','SAPONE VISO MANI CURCUMA CANNELLA',5.0,1,true,true,true,100,true,'Natyr'),
  ('Natyr','LINEA HOPE CON OLIO EVO DALLA PALESTINA','8049','CREMA MANI NUTRIENTE',null,1,true,true,true,101,true,'Natyr'),
  ('Natyr','LINEA HOPE CON OLIO EVO DALLA PALESTINA','8051','BURRO LABBRA',null,1,true,true,true,102,true,'Natyr'),
  ('Natyr','LINEA HOPE CON OLIO EVO DALLA PALESTINA','8052','CREMA CORPO NUTRIENTE',null,1,true,true,true,103,true,'Natyr'),
  ('Natyr','LINEA HOPE CON OLIO EVO DALLA PALESTINA','8053','BAGNODOCCIA DELICATO',null,1,true,true,true,104,true,'Natyr')
ON CONFLICT (product_code, source_sheet) DO NOTHING;
